# CORRECTED copy of the provided credit-card-payment-service spec. Two identical copies exist: the provider's
# (credit-card-payment-service/src/main/resources/openapi/, served by the stub) and the consumer's
# (room-reservation-service/src/main/resources/openapi/, the generated client is built from it). Change both together;
# `make check-contracts` fails if they differ. The spec as provided is kept unchanged in
# docs/contracts/credit-card-payment-api.original.yaml, so every difference below can be checked with a plain diff.
# Nothing here changes a request or response on the wire: the path, the JSON field names and the status codes are
# the provider's.
# Defects found in the original (documented in README and ADR-0011):
#   1. servers.url was "http//:localhost:9090//host/credit-card-payment-api" (malformed scheme, double slash, stray "host").
#   2. PaymentStatusResponse.status used "format: enum" with a nested list; must be "enum: [...]".
#   3. PaymentStatusResponse.status description said "Expiry date of the driving license" (copy-paste leftover).
#   4. lastUpdateDate used format "datetime"; the OpenAPI format is "date-time".
#   5. No security scheme declared; kept as-is (assumed network-internal), see ADR-0011.
# Consumer-side addition, not a defect fix:
#   6. operationId "retrievePaymentStatus" on POST /payment-status. It only names the generated client method (the
#      generator would otherwise call it paymentStatusPost); no effect on the wire.
# Deliberately NOT added: `required: [status]` on PaymentStatusResponse. The provider does not promise it, so the
# client treats a 200 without a status as a contract violation instead of the spec pretending it cannot happen.
openapi: 3.0.3
info:
  title: Credit card payment api
  description: API to retrieve status of the credit card payment
  version: 1.0.0
servers:
  - url: http://localhost:9090/credit-card-payment-api
paths:
  /payment-status:
    post:
      operationId: retrievePaymentStatus
      summary: retrieve payment status
      description: Accepts payment reference and provides the status of the payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentStatusRetrievalRequest'
      responses:
        '200':
          description: Successful response with payment status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentStatusResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Payment not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: Internal server error
components:
  schemas:
    PaymentStatusRetrievalRequest:
      type: object
      properties:
        paymentReference:
          type: string
          description: reference of the payment
          example: DL123456789
      required:
        - paymentReference
    PaymentStatusResponse:
      type: object
      properties:
        lastUpdateDate:
          type: string
          description: last updated at
          format: date-time
          example: 2017-07-21T17:32:28Z
        status:
          type: string
          enum:
            - CONFIRMED
            - REJECTED
          example: CONFIRMED
          description: Status of the credit card payment
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
