server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: room-reservation-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reservation}
    username: ${DB_USERNAME:reservation}
    password: ${DB_PASSWORD:reservation}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    admin:
      # Topics are created by infra/kafka-init, never by the application (contracts/events.md).
      auto-create: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/reservation}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

logging:
  structured:
    format:
      console: ecs

---
spring:
  config:
    activate:
      on-profile: test
